[package]
name = "server_chan"
version = "0.1.0"
authors = ["EasyChen <easychen@gmail.com>"]
edition = "2021"

[dependencies]
reqwest = "0.11"
serde_urlencoded = "0.7"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"